### ISSUE TITLE
Support - Migrate from "jlesage" image to the official "jc21" image

### ISSUE THREAD

**Issue by ansred** [jlesage/docker-nginx-proxy-manager#180]
Request:
I am trying to migrate my proxy hosts and certificates from copy image to the use the official image

Is that possible? if yes, what is the best steps to follow as I have tried before to copy and paste from one directory to another and that didn't work.

Already created issue on # https://github.com/jc21/nginx-proxy-manager/issues/1007

Current Stack I want to migrate to:

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx_Proxy_Manager_Test_App_SQLite
    restart: always
    ports:
      - '80:80'    # Public HTTP Port:
      - '443:443'  # Public HTTPS Port:
      - '8005:81'  # Admin Web Port:
    environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
        DISABLE_IPV6: 'true'
    volumes:
      - /volume1/docker/nginx-proxy-manager/Test-sqlite/data:/data
      - /volume1/docker/nginx-proxy-manager/Test-sqlite/cert:/etc/letsencrypt
```

Thanks

**Comment by jlesage** [comment]
After you copy the `/data` folder, you have to manually edit your proxy host configurations (under `/data/nginx/proxy_host/`) and change references of `listen` directives: port `4443` to port `443` and port `8080` to port `80`.

Else, share what errors you are getting so I can better see what needs to be adjusted.

**Comment by ansred** [comment]
Thanks for the quick response!

I did test to copy one proxy host "`1.conf`" from "jlesage" instance
`nginx-proxy-manager/config/nginx/proxy_host`

and copied the custom SSL cert that is using that host
`nginx-proxy-manager/config/custom_ssl/npm-1`


To the new " jc21" instance 


and the new instance crashed with the following error:

```
today at 9:15:03 PM  Disabling IPV6 in hosts
today at 9:15:03 PM  ❯ Disabling IPV6 in hosts: /data/nginx
today at 9:15:03 PM    ❯ /data/nginx/proxy_host/1.conf
today at 9:15:03 PM  nginx: [emerg] open() "/config/log/proxy_host-1.log" failed (2: No such file or directory)
today at 9:15:03 PM  finish: applet not found
today at 9:15:04 PM  Disabling IPV6 in hosts
today at 9:15:04 PM  ❯ Disabling IPV6 in hosts: /etc/nginx/conf.d
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/assets.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/block-exploits.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/force-ssl.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/ip_ranges.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/letsencrypt-acme-challenge.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/proxy.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/ssl-ciphers.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/include/resolvers.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/default.conf
today at 9:15:04 PM    ❯ /etc/nginx/conf.d/production.conf
today at 9:15:04 PM  Disabling IPV6 in hosts
```

Even though in the new instance, I can see the file "`proxy_host-1.log`"



When I deleted the proxy host "`1.conf``" I copied, I was able to start the container again.

So, I tried to use something else.

And another test I did, copied the access list from "`access`" directory from the old instance, but when restarting the container, still won't show up.

![image](https://user-images.githubusercontent.com/5244872/116834605-dd35e500-ab8c-11eb-9579-6ec637cdf067.png)


I think it's more in the SQLite database that is not updating regarding the access folder not showing the records in the UI.


For the ref:
Here is the docker compose stack I use for the new instance:

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx_Proxy_Manager_Test_App_SQLite
    restart: always
    ports:
     #- '8097:80'  # Public HTTP Port:
     #- '8098:443' # Public HTTPS Port:
      - '8005:81'  # Admin Web Port:
    environment:
        DB_SQLITE_FILE: "/data/database.sqlite"
        DISABLE_IPV6: 'true'
    volumes:
      - /volume1/docker/nginx-proxy-manager/Test-sqlite/data:/data
      - /volume1/docker/nginx-proxy-manager/Test-sqlite/cert:/etc/letsencrypt
```


Let me know what you think please.

Thanks
