### ISSUE TITLE
Not possible to log in since last upgrade

### ISSUE THREAD

**Issue by Flyingfufu** [jlesage/docker-nginx-proxy-manager#225]
Hello,

First thanks for your hard work ! Using few of your container and love it.

Now, my issue. Since the last update done today to the latest version, the proxy seems still to be working fine, but I cannot log in anymore. Looking the container log, I can see the following error coming up endlessly:

[2022-1-2] [21:23:56] [Global   ] › ✖  error     certificate.meta.dns_provider_credentials.replaceAll is not a function
[2022-1-2] [21:23:57] [Global   ] › ℹ  info      Manual db configuration already exists, skipping config creation from environment variables
[2022-1-2] [21:23:57] [Migrate  ] › ℹ  info      Current database version: none

Any idea how to fix it ?

Best regards,

**Comment by ch4ox** [comment]
I have the same issue. There's also some problems with the reverse proxy feature itself, can't access some of my machines anymore.

There's a similar issue in the official NPM repository: https://github.com/jc21/nginx-proxy-manager/issues/1717

I think I'll rollback to the previous version for the time being.

**Comment by jlesage** [comment]
Thanks for reporting, I'm looking at this.

**Comment by jlesage** [comment]
Please try the latest Docker image and let met know you still have problems.

**Comment by Flyingfufu** [comment]
Thanks Jocelyn, the install with the latest image go through correctly to the end !

Thanks again for your prompt support.

**Comment by Flyingfufu** [comment]
Thanks Jocelyn, the install with the latest image go through correctly  !

Thanks again for your prompt support.

**Comment by ch4ox** [comment]
Wow, that was fast. Working perfect, thx again!

**Comment by stavros-k** [comment]
Hey, I'm still having the same problem with `jlesage/nginx-proxy-manager:v1.24.1`
Exact same log output as the reported issue.

**Comment by jlesage** [comment]
Humm the exact same error should not be possible with the latest version.
Can you share the output of `docker inspect <container name>` command?

**Comment by stavros-k** [comment]
Hmm, it seems it was a weird caching issue on docker.
Removed `:v1.23.1` tag and let it start, and I got the mentioned errors.
Did a forced update through Unraid's GUI. And started without errors.

Sorry to keep you waiting and thanks! :)

**Comment by swoop124** [comment]
hello,

i have installed it just jet, on alpine and have the same issue.
all sites sime to work fine but i can not login. (Bad Gateway)
![grafik](https://user-images.githubusercontent.com/75502165/149749470-8d66c4e0-b12f-44d0-afd0-732f5a38a646.png)

**Comment by swoop124** [comment]
oh, i used this commandline to install it:
wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh

regards

**Comment by jlesage** [comment]
Looks like you are not using the latest Docker image version?

**Comment by swoop124** [comment]
hello,

thanks for the answer. 
I now installed version 2.9.15. as i mentioned, not in docker. And the result is the same but errormessages are little different.
![grafik](https://user-images.githubusercontent.com/75502165/149900079-73c029b8-22cf-4672-b760-45d9499bf9ac.png)

The messages occur every second. So i desidet do tested npm version 2.9.15 on docker.
But the result is the same, i can't login to web-ui --> Bad Gateway
![grafik](https://user-images.githubusercontent.com/75502165/149900523-2488e170-99b9-4f08-a695-63d8dc81321e.png)

I'am sorry, this is not the answer to the problem.
But thanks

regards

**Comment by swoop124** [comment]
i have installed npm like this:

```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    network_mode: "bridge"
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "password"
      DB_MYSQL_NAME: "npm"
    volumes:
      - /opt/npm/data:/data
      - /opt/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'password'
    volumes:
      - /opt/npm/data/mysql:/var/lib/mysql
```
