### ISSUE TITLE
Seafile in NPM

### ISSUE THREAD

**Issue by PrzemekSkw** [jlesage/docker-nginx-proxy-manager#243]
Hello, I try to get Seafile server works on my no-ip domain with NPM. It works perfect with my local address.
I have my Nextcloud and Emby installed with Dietpi-software and now I install Seafile server with docker-compose on my dietpiOS (on HP Intel miniPC).
My docker-compose looks that:
```
version: '2.0'
services:
  db:
    image: mariadb
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=.......
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached
    container_name: seafile-memcached
    restart: unless-stopped
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc
    container_name: seafile
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - ./data/app:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=.......
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=..........@gmail.com
      - SEAFILE_ADMIN_PASSWORD=..........
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=..........ddns.net/seafile
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
```
I have in NPM 
```
Details tab:
Domain: myserver.ddns.net
Schema: https
Host IP:  127.0.0.1
Port: 80

Custom location tab:
/nextcloud 
http
127.0.0.1
80

/emby
http
127.0.0.1
8096

/Seafile
http
127.0.0.1
8090
```
More details I give on Seafile folder but don't get help yet.
https://forum.seafile.com/t/looking-for-help-with-nginx-proxy-manager/16040

Regards.
