### ISSUE TITLE
The requested image's platform not match

### ISSUE THREAD

**Issue by jiatao99** [jlesage/docker-nginx-proxy-manager#268]
Try to use your docker image, and got the following error:

the requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8). I am using Ubuntu 22.04

any idea how to fix it?

Another question, after I use the web interface to grab a Let's encrypt certificate, where does it saved? I use the following docker compose:

```yaml
version: '3'
services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    container_name: nginx
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - /docker/appdata/nginx:/config:rw
```

Thanks
