### ISSUE TITLE
ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by burntoc** [jlesage/docker-nginx-proxy-manager#30]
I had this running with the example files and then I started trying to advance my config but I kept getting errors trying to connect to the database (even though it looked like some previous help nailed my issues exactly), so I ran a docker prune and deleted the files and copied the examples back in just to get back to a known good state.  now even with what should be a scratch install that worked before on the same box it's throwing the error from the title of this report.  Any suggestions?

**Comment by burntoc** [comment]
Well darn.  By way of an update, I've found that is happening with other items when I try to do a docker-compose up now so something must be stored that's become pointed to a broken area, but I don't know what that could be.  I hope that reinstalling docker and compose can fix it at least.  I'd had to reload the OS.

**Comment by jlesage** [comment]
Can you share you docker compose file?

**Comment by burntoc** [comment]
Sorry for the delayed response.  The only file I have is a new
docker-compose.yml with the text straight from the example you posted on
the site.  I'm getting that "cannot locate specified Dockerfile" error on
everything I try.

**Comment by burntoc** [comment]
So I confirmed that I CAN run the docker command for this just fine.  It's only the docker-compose using the cut and paste (using Notepad++ like I always do) that's kicking back that Dockerfile error.

**Comment by jlesage** [comment]
Note that you may still need to adjust the example for your needs, especially the `volumes` section.

What is the docker-compose command you are invoking?

The problem seems to occurs during the building stage.  If you don't want to build the image, try to add `image: jlesage/nginx-proxy-manager` to the docker-compose yaml file, like this:

```yaml
version: '3'
services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    build: .
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - "/docker/appdata/nginx-proxy-manager:/config:rw"
```

Then run:
 - `docker-compose pull` to fetch the Docker image.
 - `docker-compose up` to create and start the container.
