### ISSUE TITLE
[Bug] Deleting certificate blocks the application

### ISSUE THREAD

**Issue by toteto** [jlesage/docker-nginx-proxy-manager#322]
### Current Behavior

I have deleted a certificate while still being attached to a host. Turns out you should not do this as it will block the app.

Currently the docker container prints this logs

### Expected Behavior

- Deleting certificate that is being attached to a host doesn't block the application.
- Deleting certificate will show WARNING to the user about this action
- Deleting certificate will detach it from the host that is being attached

### Environment

- OS:
- OS version:
- CPU: 
- Docker version:
- Device model:
- Browser/OS:

### Container creation

```
name: nginxproxymanager
services:
  nginxproxymanager:
    cpu_shares: 90
    command: []
    container_name: nginxproxymanager
    deploy:
      resources:
        limits:
          memory: 1846M
        reservations:
          memory: "134217728"
    hostname: nginxproxymanager
    image: jc21/nginx-proxy-manager:2.11.2
    labels:
      icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/NginxProxyManager/icon.png
    ports:
      - target: 80
        published: "80"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
      - target: 81
        published: "81"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/nginxproxymanager/data
        target: /data
      - type: bind
        source: /DATA/AppData/nginxproxymanager/etc/letsencrypt
        target: /etc/letsencrypt
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
```

### Container log

```text
nginxproxymanager  | [1;34m❯ [1;36mStarting nginx ...[0m
nginxproxymanager  | nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/npm-6/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/npm-6/fullchain.pem, r) error:10000080:BIO routines::no such file)
```
```


### Container inspect

_No response_

### Anything else?

Related to #224
