### ISSUE TITLE
No Relevant User Found

### ISSUE THREAD

**Issue by FenixVale** [jlesage/docker-nginx-proxy-manager#41]
Currently with a new iteration of the NPM installed via the docker-compose command that generates npm_app_1 and npm_db_1 i get this error whenever i try to login with the default credentials or any other credentials

**Comment by UNlDAN** [comment]
I am too facing this issue on a brand new Ubuntu 20.04 VM with docker and docker compose. Any solution?

**Comment by UNlDAN** [comment]
```
version: "3"
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port:
      - '81:81'
    environment:
      # Use SQLite instead of MySQL to avoid initial login errors
      DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```
